name: Test and Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('pyproject.toml') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgeos-dev libproj-dev proj-data proj-bin libgdal-dev gdal-bin

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install '.[test]'

    - name: Run linting
      run: |
        python -m ruff check ppge/*.py ppge-tests/*.py

    - name: Run formatting check
      run: |
        python -m ruff format --check ppge/*.py ppge-tests/test-*.py

    - name: Run tests
      run: |
        python -m unittest ppge-tests/test-*.py ppge-tests/test-geomet/*.py -v 